declare function __DTS_BUNDLE_GENERATOR__GENERATED_NAME$1(first: number): void;
declare function __DTS_BUNDLE_GENERATOR__GENERATED_NAME$2(second: number): void;
declare class __DTS_BUNDLE_GENERATOR__GENERATED_NAME$3 {
	first: number;
}
declare class __DTS_BUNDLE_GENERATOR__GENERATED_NAME$4 {
	second: number;
}

export {
	__DTS_BUNDLE_GENERATOR__GENERATED_NAME$1 as myFunc1,
	__DTS_BUNDLE_GENERATOR__GENERATED_NAME$1 as myFunc2,
	__DTS_BUNDLE_GENERATOR__GENERATED_NAME$2 as myFunc3,
	__DTS_BUNDLE_GENERATOR__GENERATED_NAME$2 as myFunc4,
	__DTS_BUNDLE_GENERATOR__GENERATED_NAME$3 as myClass1,
	__DTS_BUNDLE_GENERATOR__GENERATED_NAME$3 as myClass2,
	__DTS_BUNDLE_GENERATOR__GENERATED_NAME$4 as myClass3,
	__DTS_BUNDLE_GENERATOR__GENERATED_NAME$4 as myClass4,
};

export {};
